### ISSUE TITLE
Is conda-forge added to channels by default?

### ISSUE THREAD

**Issue by ma-sadeghi** [conda-incubator/setup-miniconda#62] opened 2020-08-14 21:01 UTC
I manually added `conda-forge` to channels, but I get the following warning:
```
Warning: 'conda-forge' already in 'channels' list, moving to the top
```

**Comment by goanpeca** [comment] 2020-08-20 00:15
>Is conda-forge added to channels by default

No, but we update the configuration in 2 steps, the second time it happens, it may show something like this.

**Comment by ma-sadeghi** [comment] 2020-08-20 02:46
Thanks for getting back to me. Is there a way to suppress the warning?

**Comment by goanpeca** [comment] 2020-08-23 20:25
>Is there a way to suppress the warning?

Not currently, will look into for the next minor release.

**Comment by bilderbuchi** [comment] 2020-11-09 08:39
I think this is a duplicate of #57.

**Closed** 2022-11-15 16:16 UTC
Labels: type:question
