### ISSUE TITLE
The `add-path` command and `set-env` command is disabled

### ISSUE THREAD

**Issue by bradyrx** [conda-incubator/setup-miniconda#101] opened 2020-11-17 16:08 UTC
**SOLUTION**: Simply update your `goanpeca/setup-miniconda@v1` hook to `conda-incubator/setup-miniconda@v2` and the error should go away.

---

It looks like something changed to Github Actions today, as our `setup-miniconda` hook is breaking with the following error:

```python-traceback
Add "/usr/share/miniconda/condabin" to PATH
Error: Unable to process command '::add-path::/usr/share/miniconda/condabin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
/usr/share/miniconda/condabin/conda config --add pkgs_dirs /home/runner/conda_pkgs_dir
Error: Unable to process command '::set-env name=CONDA_PKGS_DIR::/home/runner/conda_pkgs_dir' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

See our error in more detail [here](https://github.com/bradyrx/esmtools/pull/99/checks?check_run_id=1411240405).

And the workflow code [here](https://github.com/bradyrx/esmtools/blob/27e58176ce8f00d1fd94279bdcfba242fd9c8de3/.github/workflows/esmtools_testing.yml#L21-L28).

I found that this is affecting other hooks, so I imagine it must be a Github Actions change. E.g., https://github.com/djjudas21/camerahub/issues/630, https://github.com/apache/incubator-tvm/issues/6925.

---

EDIT: Actually it looks like GA announced this [back in October](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/), but went into effect today.

**Comment by jaimergp** [comment] 2020-11-17 16:11
See #99.

**Comment by bradyrx** [comment] 2020-11-17 16:11
Agh, sorry, thought I was ahead of the curve here. Appreciate you guys addressing it so fast!

**Comment by goanpeca** [comment] 2020-11-17 16:12
Hi @bradyrx thanks for the report. Indeed a duplicate of #99

@jaimergp we could live this open and tag it on the issue tracker? Maybe that way is easier to find for otrher users?

**Comment by jaimergp** [comment] 2020-11-17 16:15
Oh, sure, nice idea. There might be more reports coming. Shall we also pin it for a week or so?

**Comment by goanpeca** [comment] 2020-11-17 16:16
Yep, just pinned it :)

**Comment by jaimergp** [comment] 2020-11-17 16:17
@bradyrx Can you add a little comment on your opening message stating the solution for visibility?

**Comment by jaimergp** [comment] 2020-11-17 16:18
> Yep, just pinned it :)

Dark GitHub feels wrong 😄

**Comment by bradyrx** [comment] 2020-11-17 16:21
Done, thanks guys! Easy fix and quick communication.

**Comment by valeriupredoi** [comment] 2020-11-20 13:33
cheers, guys! will buy pints if this works well for us too :beer:

**Comment by valeriupredoi** [comment] 2020-11-23 12:18
> cheers, guys! will buy pints if this works well for us too beer

it works very well with the new hooks - much appreciated, folks here! :beer:

**Comment by goanpeca** [comment] 2021-04-26 18:07
Closing this one, I think we should be fine moving forward :)

**Closed by goanpeca** 2021-04-26 18:07 UTC
Labels: reso:duplicate, type:bug
